spring:
  application:
    name: CocktailsGraphQLApi
  datasource:
    url: jdbc:mysql://localhost:3306/cocktails
    username: root
    password: 01012003s
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  http2:
    enabled: true

graphiql:
  servlet:
    maxQueryDepth: 5